name: pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.4
  dio: ^5.4.0
  equatable: ^2.0.5
  firebase_core: ^2.24.1
  firebase_crashlytics: ^3.4.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.7
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  integration_test:
    sdk: flutter
  mocktail: ^1.0.2
  test: ^1.24.9

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/images/
