name: pokemon
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  cloud_firestore: ^4.13.4
  dio: ^5.4.0
  firebase_core: ^2.24.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  go_router: ^12.1.1
  google_fonts: ^6.1.0
  intl: any
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true # Add this line
  assets:
    - assets/images/
